# Generated by Django 4.1.2 on 2023-02-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_books_alter_post_content_alter_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Books',
        ),
    ]
